language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - pip install -e .
  - pip install coverage nose
cache: pip
script:
  - nosetests --cover-erase --cover-package=eve_config --with-coverage tests